dashboard/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required
from . import views
app_name = 'dashboard'
urlpatterns = [

    path('login/', LoginView.as_view(), name="admin-login"),
    path('logout/', LogoutView.as_view(), name="admin-logout"),

    #     path('dashboard/', views.admindashboard, name='admin-dashboard'),
    path('updatepassword/', PasswordsChangeView.as_view(), name="update-password"),

    path('password-forgot/', ForgotPasswordView.as_view(), name='forgotpassword'),
    path('password-reset/<int:pk>',
         PasswordResetView.as_view(), name='passwordreset'),

    path('dashboard/', AdminDashboardView.as_view(),
         name="admin-dashboard"),


    # users
    path('user/list', UsersListView.as_view(), name="user-list"),
    path('user/create', UserCreateView.as_view(), name='user-create'),

    # room
    path('room/list/', RoomListView.as_view(), name='room-list'),
    path('room/create/', RoomCreateView.as_view(), name='room-create'),
    path('room/<int:pk>/update/',
         RoomUpdateView.as_view(), name='room-update'),
    path('room/<int:pk>/detail/',
         RoomDetailView.as_view(), name="room-detail"),
    path('room/<int:pk>/delete/',
         RoomDeleteView.as_view(), name='room-delete'),

    # room image
    path('room/image/crete/', RoomImageCreateView.as_view(),
         name='room-image-create'),

    # room category
    path('room/category/', RoomCategoryListView.as_view(), name='room_category'),
    path('room/category/create/',
         RoomCategoryCreateView.as_view(), name="room-cat-create"),
    path('room/category/<int:pk>/update/',
         RoomCategoryUpdateView.as_view(), name="room-cat-update"),
    path('room/category/<int:pk>/delete/',
         RoomCategoryDelete.as_view(), name='room-cat-delete'),


    # feature
    path('feature/list/', FeatureListView.as_view(), name="feature-list"),
    path('feature/create/', FeatureCreateView.as_view(), name='feature-create'),
    path('feature/<int:pk>/update/',
         FeatureUpdateView.as_view(), name='feature-update'),
    path('feature/<int:pk>/delete/',
         FeatureDeleteView.as_view(), name='feature-delete'),

    # image
    path('gallery/', ImageListView.as_view(), name='image-list'),
    path('image/create/', ImageCreateView.as_view(), name='image-create'),
    path('image/<int:pk>/update/', ImageUpdateView.as_view(), name='image-update'),
    path('image/<int:pk>/delete/', ImageDeleteView.as_view(), name='image-delete'),
    #     path('image/<int:pk>/detail/', ImageDetailView.as_view(), name='image_detail'),

    # news

    path('news', NewsListView.as_view(), name='news-list'),
    path('news/create', NewsCreateView.as_view(), name='news-create'),
    path('news/<int:pk>/update/', NewsUpdateView.as_view(), name='news-update'),
    path('news/<int:pk>/detail/', NewsDetailView.as_view(), name="news-detail"),
    path('news/<int:pk>/delete/', NewsDeleteView.as_view(), name='news-delete'),

    # newscomment
    path('news/comment', NewsCommentTemplateView.as_view(),
         name='news-comment-list'),
    path('news/comment/create/', NewsCommentCreateView.as_view(),
         name='news-comment-create'),
    path('news/comment/<int:pk>/update/',
         NewsCommentUpdateView.as_view(), name='news-comment-update'),
    path('news/comment/<int:pk>/detail/',
         NewsCommentDetailView.as_view(), name="news-comment-detail"),
    path('news/comment/<int:pk>/delete/',
         NewsCommentDeleteView.as_view(), name='news-comment-delete'),


    # event
    path('event/list/', EventListView.as_view(), name='event-list'),
    path('event/create/', EventCreateView.as_view(), name='event-create'),
    path('event/<int:pk>/update/', EventUpdateView.as_view(), name='event-update'),
    path('event/<int:pk>/detail/', EventDetailView.as_view(), name='event-detail'),
    path('event/<int:pk>/delete/', EventDeleteView.as_view(), name='event-delete'),

    # event_comments
    path('event/comment/list/', EventCommentTemplateView.as_view(),
         name='event-comment-list'),
    path('event/commentcreate/', EventCommentCreateView.as_view(),
         name='event-comment-create'),
    path('event/comment/<int:pk>/update/',
         EventCommentUpdateView.as_view(), name='event-comment-update'),
    path('event/comment/<int:pk>/detail/',
         EventCommentDetailView.as_view(), name='event-comment-detail'),
    path('event/comment/<int:pk>/delete/',
         EventCommentDeleteView.as_view(), name='event-comment-delete'),


    # testimonials
    path('testimonial/list/', TestimonialListView.as_view(),
         name='testimonial-list'),
    path('testimonial/create/', TestimonialCreateView.as_view(),
         name='testimonial-create'),
    path('testimonial/<int:pk>/update/',
         TestimonialUpdateView.as_view(), name='testimonial-update'),
    path('testimonial/<int:pk>/detail/',
         TestimonialDetailView.as_view(), name='testimonial-detail'),
    path('testimonial/<int:pk>/delete/',
         TestimonialDeleteView.as_view(), name='testimonial-delete'),


    # message
    path('messagelist/', MessageListView.as_view(), name='message-list'),
    path('messagecreate/', MessageCreateView.as_view(), name='message-create'),
    path('message/<int:pk>/update/',
         MessageUpdateView.as_view(), name='message-update'),
    path('message/<int:pk>/detail/',
         MessageDetailView.as_view(), name='message-detail'),
    path('message/<int:pk>/delete/',
         MessageDeleteView.as_view(), name='message-delete'),

    # reservation
    path('reservationlist/', ReservationListView.as_view(),
         name='reservation-list'),
    path('reservationcreate/', ReservationCreateView.as_view(),
         name='reservation-create'),
    path('reservation/<int:pk>/update/',
         ReservationUpdateView.as_view(), name='reservation-update'),
    path('reservation/<int:pk>/detail/',
         ReservationDetailView.as_view(), name='reservation-detail'),
    path('reservation/<int:pk>/delete/',
         ReservationDeleteView.as_view(), name='reservation-delate'),

    # servicetype
    path('service/type/list/', ServiceListView.as_view(),
         name='service-type-list'),
    path('service/type/create/', ServiceCreateView.as_view(),
         name='service-type-create'),
    path('service/type/<int:pk>/update/',
         ServiceUpdateView.as_view(), name='service-type-update'),
    path('service/type/<int:pk>/detail/',
         ServiceDetailView.as_view(), name='service-type-detail'),
    path('service/type/<int:pk>/delete/',
         ServiceDeleteView.as_view(), name='service-type-delete'),

    # servicevideo
    path('service/video/list/', ServiceVideoListView.as_view(),
         name='service-video-list'),
    path('service/video/create/', ServiceVideoCreateView.as_view(),
         name='service-video-create'),
    path('service/video/<int:pk>/update/',
         ServiceVideoUpdateView.as_view(), name='service-video-update'),
    path('service/video/<int:pk>/detail/',
         ServiceVideoDetailView.as_view(), name='service-video-detail'),
    path('service/video/<int:pk>/delete/',
         ServiceVideoDeleteView.as_view(), name='service-video-delete'),

    # contact
    path('contact/list/', ContactListView.as_view(), name='contact-list'),
    path('contact/create/', ContactCreateView.as_view(), name='contact-create'),
    path('contact/<int:pk>/update/',
         ContactUpdateView.as_view(), name='contact-update'),
    path('contact/<int:pk>/detail/',
         ContactDetailView.as_view(), name='contact-detail'),
    path('contact/<int:pk>/delete/',
         ContactDeleteView.as_view(), name='contact-delete'),

    # About
    path('about/list/', AboutView.as_view(), name="about-list"),
    path('about/create/', AboutCreateView.as_view(), name="about-create"),
    path('about/<int:pk>/update/', AboutUpdateView.as_view(), name="about-update"),
    path('about/<int:pk>/detail/', AboutDetailView.as_view(), name="about-detail"),
    path('about/<int:pk>/delete/', AboutDeleteView.as_view(), name="about-delete"),

    # room-comment

    path('room/comment/list/', RoomCommentListView.as_view(),
         name='room-comment-list'),
    path('room/commentcreate/', RoomCommentCreateView.as_view(),
         name='room-comment-create'),
    path('room/comment/<int:pk>/update/',
         RoomCommentUpdateView.as_view(), name='room-comment-update'),
    path('room/comment/<int:pk>/detail/',
         RoomCommentDetailView.as_view(), name='room-comment-detail'),
    path('room/comment/<int:pk>/delete/',
         RoomCommentDeleteView.as_view(), name='room-comment-delete'),

    # newsletter

    path('newsletter/list/', NewsletterListView.as_view(), name='newsletter-list'),
    path('newsletter/<int:pk>/delete/',
         NewsletterDeleteView.as_view(), name='newsletter-delete'),
    # user disable
    path('userdisable/<int:pk>/',
         UserToggleStatusView.as_view(), name='user_disable'),


]

hms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('', include("dashboard.urls")),
  
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User, Group
import datetime
from django.utils import timezone

# Create your models here.
ADULT = (
        ('1', '1 Adult'),
        ('2', '2 Adults'),
        ('3', '3 Adults'),
)
CHILDREN = (
    ('0', '0 child'),
    ('1', '1 child'),
    ('2', '2 children'),
    ('3', '3 children'),
)


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self, hard=False):
        if not hard:
            self.deleted_at = timezone.now()
            return super().save()
        else:
            return super().delete()


class About(TimeStamp):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="about")
    description = RichTextField()

    def __str__(self):
        return self.title


class Room_Category(TimeStamp):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Feature(TimeStamp):
    title = models.CharField(max_length=250)
    image = models.ImageField(upload_to="features")

    class Meta:
        verbose_name = _('Feature')
        verbose_name_plural = _('Features')

    def __str__(self):
        return self.title


class RoomImage(TimeStamp):
    image = models.ImageField(upload_to="room")
    

class Room(TimeStamp):
    room_type = models.ForeignKey(Room_Category, on_delete=models.CASCADE)
    room_no = models.CharField(
        max_length=250, primary_key=True)
    description = RichTextField()
    checked_in_date = models.DateField(null=True, blank=True)
    checked_out_date = models.DateField(null=True, blank=True)
    availability = models.BooleanField(default=False)
    price = models.PositiveIntegerField()
    image = models.ManyToManyField(RoomImage)
    features = models.ManyToManyField(Feature)

    class Meta:
        verbose_name = _('Room')
        verbose_name_plural = _('Rooms')

    def __str__(self):
        return self.room_no


class Image(TimeStamp):
    image_type = models.ForeignKey(Room_Category, on_delete=models.CASCADE)
    caption = models.CharField(max_length=100)
    image = models.ImageField(upload_to='gallery')

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Images')

    def __str__(self):
        return self.caption


class Testomonial(TimeStamp):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='Testimonials', null=True, blank=True)
    profession = models.CharField(max_length=255, null=True, blank=True)
    voice = models.TextField()

    class Meta:
        verbose_name = _('Testimonial')
        verbose_name_plural = _('Testimonials')

    def __str__(self):
        return self.name


class News(TimeStamp):
    title = models.CharField(max_length=1255)
    image = models.ImageField(upload_to="News")
    description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    view_count = models.PositiveIntegerField(default=0, null=True, blank=True)

    class Meta:
        verbose_name = _('News')
        verbose_name_plural = _('News')

    def __str__(self):
        return self.title


class Event(TimeStamp):
    title = models.CharField(max_length=1255)
    image = models.ImageField(upload_to="Events")
    description = RichTextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    view_count = models.PositiveIntegerField(default=0, null=True, blank=True)

    class Meta:
        verbose_name = _('Event')
        verbose_name_plural = _('Events')

    def __str__(self):
        return self.title


class Comment(TimeStamp):
    full_name = models.CharField(max_length=30)
    email = models.EmailField()
    website = models.URLField(null=True, blank=True)
    room = models.ForeignKey(
        Room, related_name='room_comment', on_delete=models.CASCADE, null=True, blank=True)
    news = models.ForeignKey(
        News, related_name="news_comment", on_delete=models.CASCADE, null=True, blank=True)
    events = models.ForeignKey(
        Event, related_name="event_comment", on_delete=models.CASCADE, null=True, blank=True)
    comment = models.TextField()

    class Meta:
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')

    def __str__(self):
        return self.full_name


class Contact(TimeStamp):
    address = models.CharField(max_length=100)
    phone = models.PositiveIntegerField()
    fax = models.PositiveIntegerField(null=True, blank=True)
    email = models.EmailField()


class Message(TimeStamp):
    full_name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        verbose_name = _('Message')
        verbose_name_plural = _('Messages')

    def __str__(self):
        return self.full_name


class Reservation(TimeStamp):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    selected_room = models.ForeignKey(
        Room, on_delete=models.CASCADE)
    check_in_date = models.DateTimeField()
    check_out_date = models.DateTimeField()
    adult = models.CharField(max_length=250, choices=ADULT)
    children = models.CharField(max_length=250, choices=CHILDREN)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=40)
    address_1 = models.CharField(max_length=255)
    address_2 = models.CharField(max_length=255, null=True, blank=True)
    state = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    zip_code = models.CharField(max_length=250, null=True, blank=True)
    country = models.CharField(max_length=40)
    special_req = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = _('Reservation')
        verbose_name_plural = _('Reservations')

    def __str__(self):
        return self.first_name + self.last_name


class Services_description(TimeStamp):
    description = models.CharField(max_length=200)
    service_video = models.FileField(upload_to="service_description")

    def __str__(self):
        return self.description


class Services_type(TimeStamp):
    service_type_name = models.CharField(max_length=100)
    service_png = models.ImageField(upload_to="service_type")
    service_type_description = models.CharField(max_length=200)

    def __str__(self):
        return self.service_type_name


class Subscription(TimeStamp):
    email = models.EmailField()

    def __str__(self):
        return self.email


class Account(User):
    mobile = models.CharField(max_length=250)
    address = models.CharField(max_length=250)
    image = models.ImageField(upload_to='user')

    def __str__(self):
        return self.username

dashboard/templates/dashboard/services-type/detail.html
{% extends 'dashboard/base/index.html' %} 
{% block content %}

<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Service Type Detail</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Service Type Detail</li>
            </ol>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <button class="btn btn-primary">
            <a class="text-white" href="{% url 'dashboard:service-type-list' %}"
              >Cancel</a
            >
          </button>
          <div class="card-tools">
            <button
              type="button"
              class="btn btn-tool"
              data-card-widget="collapse"
              title="Collapse"
            >
              <i class="fas fa-minus"></i>
            </button>
            <button
              type="button"
              class="btn btn-tool"
              data-card-widget="remove"
              title="Remove"
            >
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
              <div class="row">
                <div class="col-12">
                  <h4>Service Type</h4>
                  <div class="post">
                    <div class="user-block">
                      <span class="service-name"
                        >{{servicedetail.service_type_name }}</span
                      >
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <h4>Service Details</h4>
                  <div class="post">
                    <div class="user-block">
                      <span class="description">{{servicedetail.service_type_description}}</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <h4>Service Image</h4>
                  <div class="post">
                    <div class="user-block">
                    <img
                        style="height: 20rem; width: 20rem"
                        src="{{servicedetail.service_png.url}}"
                        alt="Service image"
                    />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>

{% endblock %}

dashboard/templates/dashboard/services-type/form.html
{% extends 'dashboard/base/index.html' %} 
{% block content %}

<div class="wrapper">
  <div class="content-wrapper">
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2"> 
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-left">
              <li class="breadcrumb-item">
                <a href="{% url 'dashboard:admin-dashboard' %}">Home</a>
              </li>
              <li class="breadcrumb-item active">Service Type</li>
            </ol>
          </div>
        
         
        </div>
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-10 mx-auto">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add / Edit Services</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-body">
                  {% comment %} {{ form }} {% endcomment %}
                  <div class="form-group">
                    <label for="service-type">Service Type</label>
                    <p>{{form.service_type_name}}</p>
                  </div>
                  <div class="form-group">
                    <label for="service-type-description">Service Description</label>
                    <p>{{form.service_type_description}}</p>
                  </div>
                  <div class="form-group">
                    <label for="service-image">Image</label>
                    <p>{{form.service_png}}</p>
                  </div>
                </div>

                <!-- /.card-body -->

               <div class="card-footer float-right">
                  <button type="submit" class="btn btn-primary ">Submit</button>
                   <button class="btn btn-secondary">
                   <a class="text-white" href="{% url 'dashboard:service_type_list' %}">Cancel</a>
                   </button>
                </div>
              </form>
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
{% endblock %}

dashboard/templates/dashboard/services-type/list.html
{% extends 'dashboard/base/index.html' %} {% block content %}

<div class="wrapper">
  <div class="content-wrapper">
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
         <div class="col-sm-6">
            <ol class="breadcrumb float-sm-left">
              <li class="breadcrumb-item">
                <a href="{% url 'dashboard:admin-dashboard' %}">Home</a>
              </li>
              <li class="breadcrumb-item active">Service Type</li>
            </ol>
          </div>
          <div class="col-sm-6">
            <button class="btn btn-primary float-sm-right">
              <a
                class="text-white"
                href="{% url 'dashboard:service-type-create' %}"
                >Add Services</a
              >
            </button>
          </div>
         
        </div>
      </div>
      <!-- /.container-fluid -->
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Service Type List</h3>

                <div class="card-tools">
                  <div class="input-group">
                    <form
                      action="{% url 'dashboard:service-type-list' %}"
                      method="GET"
                      class="form-inline"
                    >
                      <input
                        type="text"
                        name="service_type_name"
                        class="form-control float-right searchInput"
                        id="service_type_name "
                        placeholder="Service Type"
                      />
                   
                        <button type="submit" class="btn btn-default">
                          <i class="fas fa-search"></i>
                        </button>
                     
                    </form>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                  <thead>
                    <tr>
                      <th>SN</th>
                      <th>Service Type</th>
                      <th>Description</th>
                      <th>Image</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for service in object_list %}
                    <tr>
                      <td>{{forloop.counter}}</td>
                      <td>
                        <a
                          href="{%url 'dashboard:service-type-detail' service.id%}"
                          >{{service.service_type_name}}</a
                        >
                      </td>
                      <td>
                        {{service.service_type_description|truncatewords:10}}
                      </td>
                      <td>
                        <img
                          src="{{service.service_png.url}}"
                          style="width: 20%"
                        />
                      </td>
                      <td>
                        <span
                          ><a
                            class="btn btn-warning mr-2"
                            href="{% url 'dashboard:service-type-update' service.id %}"
                            ><i class="fa fa-edit m-1" aria-hidden="true"></i
                            >Edit</a
                          ></span
                        >
                        <span
                          ><a
                            class="btn btn-danger delete"
                            href="{% url 'dashboard:service-type-delete' service.id %}"
                            ><i class="fa fa-trash m-1"></i></a
                        ></span>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
{% endblock %}
{% block script %}
<script>
$('.delete').click(function(e) {
        e.preventDefault();
        swal({
                title: "Are you sure?",
                text: "It will permanently deleted !",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                  window.location.href = $(this).attr('href');
                    swal(" 'Your file has been deleted.'!", {
                        icon: "success",
                    });

                }
            });
    })
</script>
{% endblock %}